changelog:
  categories:
    - title: 🎉 Features
      labels:
        - features
    - title: 🛠️ Changes
      labels:
        - changes
    - title: 🐛 Bug Fixes
      labels:
        - bugfix
    - title: ⚡ Refactoring
      labels:
        - refactoring
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 📖 Documents
      labels:
        - documents
    - title: 👀 Other Changes
      labels:
        - "*"
