name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Go build
        run: (cd api && go build -v -o app ./...)

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: yarn install
        run: (cd ui && yarn install)

      - name: yarn build
        run: (cd ui && yarn build)

      - name: Compress ui
        run: (cd ui && tar -zcvf ui.tar.gz ./dist/)

      - name: Create release note
        id: create_release_note
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: false
          prerelease: false

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.create_release_note.outputs.body }}
          files: |
            api/app
            ui/ui.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
