name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Go build for windows amd64
        run: (cd api && GOOS=windows GOARCH=amd64 go build -v -o app_windows_amd64.exe ./main.go)

      - name: Go build for windows arm
        run: (cd api && GOOS=windows GOARCH=arm go build -v -o app_windows_arm.exe ./main.go)

      - name: Go build for darwin amd64
        run: (cd api && GOOS=darwin GOARCH=amd64 go build -v -o app_darwin_amd64 ./main.go)

      - name: Go build for darwin arm64
        run: (cd api && GOOS=darwin GOARCH=arm64 go build -v -o app_darwin_arm64 ./main.go)

      - name: Go build for linux amd64
        run: (cd api && GOOS=linux GOARCH=amd64 go build -v -o app_linux_amd64 ./main.go)

      - name: Go build for linux arm64
        run: (cd api && GOOS=linux GOARCH=arm64 go build -v -o app_linux_arm64 ./main.go)

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: ./ui/yarn.lock

      - name: yarn install
        run: (cd ui && yarn install)

      - name: yarn build
        run: (cd ui && yarn build)

      - name: Compress ui
        run: (cd ui/dist && tar -zcvf ../front.tar.gz .)

      - name: Create release
        run: gh release create ${{ github.ref_name }} --generate-notes "api/app_windows_amd64.exe" "api/app_windows_arm.exe" "api/app_darwin_amd64" "api/app_darwin_arm64" "api/app_linux_amd64" "api/app_linux_arm64" "ui/front.tar.gz"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Actionsのパッケージでいい感じにやるなら...
      # - name: Create release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     generate_release_notes: true
      #     draft: false
      #     prerelease: false
      #     files: |
      #       api/app_windows_amd64.exe
      #       api/app_windows_arm.exe
      #       api/app_darwin_amd64
      #       api/app_darwin_arm64
      #       api/app_linux_amd64
      #       api/app_linux_arm64
      #       ui/front.tar.gz
